//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DodatniTretmani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DodatniTretmani()
        {
            this.DodatniTretmaniOcjenes = new HashSet<DodatniTretmaniOcjene>();
            this.Terminis = new HashSet<Termini>();
            this.Skladistes = new HashSet<Skladiste>();
        }
    
        public int TretmanID { get; set; }
        public string NazivTretmana { get; set; }
        public int Cijena { get; set; }
        public string Opis { get; set; }
        public int VrstaUslugeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DodatniTretmaniOcjene> DodatniTretmaniOcjenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termini> Terminis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skladiste> Skladistes { get; set; }
        public virtual VrsteUsluga VrsteUsluga { get; set; }
    }
}
