//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usluge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usluge()
        {
            this.Terminis = new HashSet<Termini>();
            this.UslugeOcjenes = new HashSet<UslugeOcjene>();
        }
    
        public int UslugaID { get; set; }
        public string NazivUsluge { get; set; }
        public int TrajanjeMinute { get; set; }
        public decimal CijenaUsluge { get; set; }
        public int VrstaUslugeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termini> Terminis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UslugeOcjene> UslugeOcjenes { get; set; }
        public virtual VrsteUsluga VrsteUsluga { get; set; }
    }
}
