//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHairdresserSalon_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eHairdresserSalon_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o  klijentu!.
        /// </summary>
        internal static string add_usr_succ {
            get {
                return ResourceManager.GetString("add_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno je označiti klijenta!.
        /// </summary>
        internal static string appClient_req {
            get {
                return ResourceManager.GetString("appClient_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum termina je obavezan!.
        /// </summary>
        internal static string appDate_req {
            get {
                return ResourceManager.GetString("appDate_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno je označiti frizera!.
        /// </summary>
        internal static string appHairdresser_req {
            get {
                return ResourceManager.GetString("appHairdresser_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno je označiti uslugu!.
        /// </summary>
        internal static string appService_req {
            get {
                return ResourceManager.GetString("appService_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijeme termina je obavezno!.
        /// </summary>
        internal static string appTime_req {
            get {
                return ResourceManager.GetString("appTime_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv tretmana je obavezan!.
        /// </summary>
        internal static string atName_req {
            get {
                return ResourceManager.GetString("atName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena tretmana je obavezna!.
        /// </summary>
        internal static string atPrice_req {
            get {
                return ResourceManager.GetString("atPrice_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum takmičenja je obavezan!.
        /// </summary>
        internal static string cDate_req {
            get {
                return ResourceManager.GetString("cDate_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv takmičenja je obavezan!.
        /// </summary>
        internal static string cName_req {
            get {
                return ResourceManager.GetString("cName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mjesto takmičenja je obavezno!.
        /// </summary>
        internal static string cPlace_req {
            get {
                return ResourceManager.GetString("cPlace_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o dodatnom tretmanu!.
        /// </summary>
        internal static string edit_addT_succ {
            get {
                return ResourceManager.GetString("edit_addT_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o terminu!.
        /// </summary>
        internal static string edit_appo_succ {
            get {
                return ResourceManager.GetString("edit_appo_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o takmičenju!.
        /// </summary>
        internal static string edit_com_succ {
            get {
                return ResourceManager.GetString("edit_com_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o nagradi!.
        /// </summary>
        internal static string edit_gift_succ {
            get {
                return ResourceManager.GetString("edit_gift_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o frizeru!.
        /// </summary>
        internal static string edit_hairD_succ {
            get {
                return ResourceManager.GetString("edit_hairD_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o proizvodu!.
        /// </summary>
        internal static string edit_pro_succ {
            get {
                return ResourceManager.GetString("edit_pro_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o usluzi!.
        /// </summary>
        internal static string edit_ser_succ {
            get {
                return ResourceManager.GetString("edit_ser_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili količinu na skladištu!.
        /// </summary>
        internal static string edit_st_succ {
            get {
                return ResourceManager.GetString("edit_st_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o  klijentu!.
        /// </summary>
        internal static string edit_usr_succ {
            get {
                return ResourceManager.GetString("edit_usr_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresa je zauzeta!.
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je u pogresnom formatu!.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan!.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno!.
        /// </summary>
        internal static string fName_req {
            get {
                return ResourceManager.GetString("fName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv nagrade je obavezan!.
        /// </summary>
        internal static string gName_req {
            get {
                return ResourceManager.GetString("gName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos količine proizvoda je obavezan!.
        /// </summary>
        internal static string kol_req {
            get {
                return ResourceManager.GetString("kol_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno!.
        /// </summary>
        internal static string lName_req {
            get {
                return ResourceManager.GetString("lName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste neispravnu lozinku..
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime nije pronađeno ili je Vaš nalog neaktivan..
        /// </summary>
        internal static string login_user_err {
            get {
                return ResourceManager.GetString("login_user_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka ne smije biti manja od 6 karaktera, mora sadržavati najmanje jedan broj, te malo i veliko slovo!.
        /// </summary>
        internal static string lozinka_err {
            get {
                return ResourceManager.GetString("lozinka_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna!.
        /// </summary>
        internal static string lozinka_req {
            get {
                return ResourceManager.GetString("lozinka_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruka o uspjehu.
        /// </summary>
        internal static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra je zauzeta!.
        /// </summary>
        internal static string pCode_con {
            get {
                return ResourceManager.GetString("pCode_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra proizvoda je obavezna!.
        /// </summary>
        internal static string pCode_req {
            get {
                return ResourceManager.GetString("pCode_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebno je da odaberete sliku dimenzija većih od.
        /// </summary>
        internal static string picture_war {
            get {
                return ResourceManager.GetString("picture_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv proizvoda je obavezan!.
        /// </summary>
        internal static string pName_req {
            get {
                return ResourceManager.GetString("pName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina proizvoda je obavezna!.
        /// </summary>
        internal static string pQuantity_req {
            get {
                return ResourceManager.GetString("pQuantity_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje usluge izrazeno u minutama je obavezno!.
        /// </summary>
        internal static string sDuration_req {
            get {
                return ResourceManager.GetString("sDuration_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno je označiti vrstu usluge!.
        /// </summary>
        internal static string serviceType_req {
            get {
                return ResourceManager.GetString("serviceType_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv usluge je obavezan!.
        /// </summary>
        internal static string sName_req {
            get {
                return ResourceManager.GetString("sName_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena usluge je obavezna!.
        /// </summary>
        internal static string sPrice_req {
            get {
                return ResourceManager.GetString("sPrice_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno!.
        /// </summary>
        internal static string usr_req {
            get {
                return ResourceManager.GetString("usr_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite korisničko ime i lozinku!.
        /// </summary>
        internal static string usr_usr_req {
            get {
                return ResourceManager.GetString("usr_usr_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
