
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace eHairdresserSalon_API.Models
{

using System;
    
public partial class Frizeri_Result2
{

    public int FrizerID { get; set; }

    public string ImePrezime { get; set; }

    public string Naziv_usluge { get; set; }

    public Nullable<int> Ocjena_usluge { get; set; }

    public string Naziv_tretmana { get; set; }

    public Nullable<int> Ocjena_tretmana { get; set; }

    public Nullable<decimal> Prosječna_ocjena { get; set; }

}

}
