
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace eHairdresserSalon_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Klijenti
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Klijenti()
    {

        this.Termini = new HashSet<Termini>();

        this.DodatniTretmaniOcjene = new HashSet<DodatniTretmaniOcjene>();

        this.UslugeOcjene = new HashSet<UslugeOcjene>();

        this.KlijentiTakmicenja = new HashSet<KlijentiTakmicenja>();

        this.KlijentiNagrade = new HashSet<KlijentiNagrade>();

    }


    public int KlijentID { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public Nullable<System.DateTime> DatumRodjenja { get; set; }

    public string Adresa { get; set; }

    public string Email { get; set; }

    public string BrojTelefona { get; set; }

    public string Napomena { get; set; }

    public string KorisnickoIme { get; set; }

    public string LozinkaSalt { get; set; }

    public string LozinkaHash { get; set; }

    public Nullable<int> TerminiCount { get; set; }

    public Nullable<bool> Aktivan { get; set; }



    public virtual Klijenti Klijenti1 { get; set; }

    public virtual Klijenti Klijenti2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Termini> Termini { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DodatniTretmaniOcjene> DodatniTretmaniOcjene { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UslugeOcjene> UslugeOcjene { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KlijentiTakmicenja> KlijentiTakmicenja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KlijentiNagrade> KlijentiNagrade { get; set; }

}

}
