
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace eHairdresserSalon_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class KlijentiNagrade
{

    public int NagradaID { get; set; }

    public int KlijentID { get; set; }

    public System.DateTime DatumPrijave { get; set; }



    public virtual Klijenti Klijenti { get; set; }

    public virtual Nagrade Nagrade { get; set; }

}

}
