
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace eHairdresserSalon_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Takmicenja
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Takmicenja()
    {

        this.KlijentiTakmicenja = new HashSet<KlijentiTakmicenja>();

    }


    public int TakmicenjeID { get; set; }

    public string Naziv { get; set; }

    public System.DateTime Datum { get; set; }

    public string Mjesto { get; set; }

    public string Opis { get; set; }

    public Nullable<int> FrizerID { get; set; }



    public virtual Frizeri Frizeri { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KlijentiTakmicenja> KlijentiTakmicenja { get; set; }

}

}
