
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace eHairdresserSalon_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Termini
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Termini()
    {

        this.UslugeOcjene = new HashSet<UslugeOcjene>();

    }


    public int TerminID { get; set; }

    public System.DateTime Datum { get; set; }

    public System.TimeSpan Vrijeme { get; set; }

    public Nullable<int> KlijentID { get; set; }

    public Nullable<int> FrizerID { get; set; }

    public Nullable<int> UslugaID { get; set; }

    public Nullable<bool> Zauzeto { get; set; }

    public Nullable<int> TretmanID { get; set; }

    public Nullable<bool> OcijenjenaUsluga { get; set; }

    public Nullable<bool> OcijenjenTretman { get; set; }

    public Nullable<bool> prosaoTermin { get; set; }



    public virtual Frizeri Frizeri { get; set; }

    public virtual Klijenti Klijenti { get; set; }

    public virtual Usluge Usluge { get; set; }

    public virtual DodatniTretmani DodatniTretmani { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UslugeOcjene> UslugeOcjene { get; set; }

}

}
